# Generated by Django 5.1.1 on 2024-10-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20200404_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(blank=True, choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('bool', 'bool'), ('json', 'json')], default='str', max_length=8, verbose_name='Type'),
        ),
    ]
